FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive \
  apt-get install -y --no-install-recommends \
    iputils-ping \
    less \
    net-tools \
    nmap \
    strace \
    tcpdump \
    tshark \
    vim \
    wget && \
  rm -rf /var/lib/apt/*
