#!/usr/bin/perl -w
#
# -*- perl -*-
#

use strict;
use Munin::Plugin::SNMP;

if (defined $ARGV[0] and $ARGV[0] eq "config") {
    my ($host) = Munin::Plugin::SNMP->config_session();
        print "host_name $host\n" unless $host eq 'localhost';
        print "graph_title ADSL SNR\n";
	print "graph_order down_snr up_snr\n";
	print "graph_args --base 1000\n";
	print "graph_vlabel SNR down (-) / up (+)\n";
	print "down_snr.type GAUGE\n";
	print "down_snr.graph no\n";
	print "up_snr.label SNR down/up\n";
	print "up_snr.type GAUGE\n";
	print "up_snr.negative down_snr\n";
        exit 0;
}

my $session = Munin::Plugin::SNMP->session(-translate =>
                                           [ -timeticks => 0x0 ]);

my $down_snr = $session->get_single (".1.3.6.1.2.1.10.94.1.1.2.1.4.3") || 'U';
my $up_snr = $session->get_single (".1.3.6.1.2.1.10.94.1.1.3.1.4.3") || 'U';

print "down_snr.value ", $down_snr, "\n";
print "up_snr.value ", $up_snr, "\n";

